<?php

namespace Voyage\VoyageBundle\Repository;

/**
 * assuranceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class assuranceRepository extends \Doctrine\ORM\EntityRepository
{
}
