<?php

namespace Voyage\VoyageBundle\Repository;

/**
 * continentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class continentRepository extends \Doctrine\ORM\EntityRepository
{
}
