<?php

namespace Voyage\VoyageBundle\Repository;

/**
 * dateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class dateRepository extends \Doctrine\ORM\EntityRepository
{
}
