<?php

namespace Voyage\VoyageBundle\Repository;

/**
 * hotelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class hotelRepository extends \Doctrine\ORM\EntityRepository
{
}
