<?php

namespace Voyage\VoyageBundle\Repository;

/**
 * prixRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class prixRepository extends \Doctrine\ORM\EntityRepository
{
}
