<?php

namespace Voyage\VoyageBundle\Repository;

/**
 * reductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reductionRepository extends \Doctrine\ORM\EntityRepository
{
}
