<?php

namespace Voyage\VoyageBundle\Repository;

/**
 * type_personneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class type_personneRepository extends \Doctrine\ORM\EntityRepository
{
}
