<?php

namespace Voyage\VoyageBundle\Repository;

/**
 * type_voyageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class type_voyageRepository extends \Doctrine\ORM\EntityRepository
{
}
